import os
import datetime
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from typing import Dict, Any
from sqlalchemy.orm import Session
from backend.config import REPORTS_DIR
from backend.models.file import UploadedFile
from backend.services.file_service import extract_file_content

def generate_powerpoint_presentation(title: str, text_content: str, output_dir: str) -> str:
    """
    Generates a PowerPoint presentation (.pptx) based on report content or document summary.
    Returns file path of the generated PPTX.
    """
    prs = Presentation()

    # Slide 1: Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_box = slide.shapes.title
    subtitle_box = slide.placeholders[1]

    title_box.text = title
    subtitle_box.text = f"Automated Executive Presentation\nGenerated by SurveySnap AI Engine • {datetime.datetime.now().strftime('%B %d, %Y')}"

    # Break text content into section slides
    paragraphs = [p.strip() for p in text_content.split('\n\n') if p.strip()]

    # Slide 2: Executive Highlights
    bullet_slide_layout = prs.slide_layouts[1]
    slide2 = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide2.shapes
    title_shape = shapes.title
    title_shape.text = "Executive Summary & Core Key Points"
    body_shape = shapes.placeholders[1]

    tf = body_shape.text_frame
    tf.word_wrap = True

    for p in paragraphs[:5]:
        p_item = tf.add_paragraph()
        p_item.text = p[:150] + ("..." if len(p) > 150 else "")
        p_item.level = 0

    # Slide 3: Recommendations & Strategy
    slide3 = prs.slides.add_slide(bullet_slide_layout)
    slide3.shapes.title.text = "Strategic AI Recommendations"
    tf3 = slide3.shapes.placeholders[1].text_frame
    tf3.word_wrap = True

    recs = [
        "Optimize data normalization and continuous metric scaling for predictive stability.",
        "Impute missing entries to eliminate bias in downstream intelligence reports.",
        "Deploy automated alert monitors for real-time anomaly detection."
    ]
    for r in recs:
        p_item = tf3.add_paragraph()
        p_item.text = r
        p_item.level = 0

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    clean_title = "".join([c if c.isalnum() else "_" for c in title])
    output_filename = f"Presentation_{clean_title}_{timestamp}.pptx"
    output_path = os.path.join(output_dir, output_filename)

    prs.save(output_path)
    return output_path

def create_presentation_from_file(db: Session, file_id: int, title: str = "Executive Presentation") -> Dict[str, Any]:
    file_record = db.query(UploadedFile).filter(UploadedFile.id == file_id).first()
    if not file_record or not os.path.exists(file_record.storage_location):
        return {"error": "File not found"}

    content = extract_file_content(file_record.storage_location, file_record.file_type)
    text = content.get("text", "")
    out_path = generate_powerpoint_presentation(title, text, str(REPORTS_DIR))
    return {"message": "Presentation generated", "output_path": out_path}
