import os
import datetime
import docx
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from typing import Dict, Any
from sqlalchemy.orm import Session
from backend.config import REPORTS_DIR

def generate_report(title: str, analytics_data: Dict[str, Any], output_dir: str, format_type: str = "pdf") -> str:
    """
    Generates a professional executive intelligence report in PDF, DOCX, HTML, or Markdown format.
    Returns the file path of the generated report.
    """
    format_type = format_type.lower()
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    clean_title = "".join([c if c.isalnum() else "_" for c in title])
    filename = f"Report_{clean_title}_{timestamp}.{format_type}"
    file_path = os.path.join(output_dir, filename)

    summary = analytics_data.get("summary", {})
    stats = analytics_data.get("statistics", {})
    trends = analytics_data.get("trends", [])
    recommendations = analytics_data.get("recommendations", [])
    risk = analytics_data.get("risk_analysis", {})

    if format_type == "pdf":
        doc = SimpleDocTemplate(
            file_path,
            pagesize=letter,
            rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40
        )
        styles = getSampleStyleSheet()

        # Custom ReportLab Styles
        title_style = ParagraphStyle('ReportTitle', parent=styles['Heading1'], fontSize=22, textColor=colors.HexColor('#6366f1'), spaceAfter=10)
        subtitle_style = ParagraphStyle('ReportSub', parent=styles['Normal'], fontSize=10, textColor=colors.HexColor('#64748b'), spaceAfter=15)
        h2_style = ParagraphStyle('ReportH2', parent=styles['Heading2'], fontSize=14, textColor=colors.HexColor('#0f172a'), spaceBefore=12, spaceAfter=8)
        body_style = ParagraphStyle('ReportBody', parent=styles['Normal'], fontSize=10, textColor=colors.HexColor('#334155'), leading=14, spaceAfter=6)

        story = []

        # Title Block
        story.append(Paragraph(title, title_style))
        story.append(Paragraph(f"Generated by SurveySnap AI Engine • Date: {datetime.datetime.now().strftime('%B %d, %Y')}", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#6366f1'), spaceAfter=15))

        # Executive Summary
        story.append(Paragraph("1. Executive Summary", h2_style))
        exec_text = f"This document presents an automated intelligence analysis. The analyzed dataset consists of {summary.get('total_records', 0)} total records across {summary.get('total_columns', 0)} data fields. Data quality score indicates a missing value density of {summary.get('missing_percentage', 0)}%."
        story.append(Paragraph(exec_text, body_style))
        story.append(Spacer(1, 10))

        # Key Metrics Table
        story.append(Paragraph("2. Primary Statistical Overview", h2_style))
        table_data = [["Metric / Column", "Mean", "Median", "Min", "Max", "Std Dev"]]
        for col_name, col_stat in list(stats.items())[:6]:
            table_data.append([
                col_name[:15],
                str(col_stat.get("mean", "")),
                str(col_stat.get("median", "")),
                str(col_stat.get("min", "")),
                str(col_stat.get("max", "")),
                str(col_stat.get("std", ""))
            ])

        if len(table_data) > 1:
            t = Table(table_data, colWidths=[120, 80, 80, 80, 80, 80])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6366f1')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8fafc')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ]))
            story.append(t)
            story.append(Spacer(1, 15))

        # Risk & Trends
        story.append(Paragraph("3. Risk & Trend Assessment", h2_style))
        risk_text = f"Overall Data Risk Index: <b>{risk.get('score', 0)}/100 ({risk.get('level', 'Low')} Risk)</b>.<br/>"
        if risk.get('factors'):
            risk_text += "Key Observations: " + ", ".join(risk.get('factors'))
        story.append(Paragraph(risk_text, body_style))
        story.append(Spacer(1, 10))

        # Recommendations
        story.append(Paragraph("4. AI Strategic Recommendations", h2_style))
        for rec in recommendations:
            story.append(Paragraph(f"• {rec}", body_style))

        doc.build(story)

    elif format_type == "docx":
        doc = docx.Document()
        doc.add_heading(title, level=1)
        doc.add_paragraph(f"Generated by SurveySnap AI Engine on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")

        doc.add_heading("Executive Summary", level=2)
        doc.add_paragraph(f"Dataset contains {summary.get('total_records', 0)} records and {summary.get('total_columns', 0)} variables.")

        doc.add_heading("Strategic Recommendations", level=2)
        for rec in recommendations:
            doc.add_paragraph(rec, style='List Bullet')

        doc.save(file_path)

    elif format_type == "html":
        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title}</title>
    <style>
        body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0b0a16; color: #e2e8f0; padding: 40px; max-width: 900px; margin: auto; }}
        h1 {{ color: #a855f7; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }}
        h2 {{ color: #38bdf8; margin-top: 30px; }}
        .card {{ background: rgba(255,255,255,0.05); padding: 20px; border-radius: 12px; border: 1px solid rgba(255,255,255,0.1); margin-bottom: 20px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
        th, td {{ border: 1px solid #334155; padding: 10px; text-align: left; }}
        th {{ background: #4338ca; color: #fff; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p><i>Generated by SurveySnap AI Engine • {datetime.datetime.now().strftime('%B %d, %Y')}</i></p>
    
    <div class="card">
        <h2>Executive Summary</h2>
        <p>Total Records: {summary.get('total_records', 0)} | Columns: {summary.get('total_columns', 0)} | Missing Data: {summary.get('missing_percentage', 0)}%</p>
    </div>

    <div class="card">
        <h2>Risk Assessment</h2>
        <p>Risk Score: <strong>{risk.get('score', 0)}/100 ({risk.get('level', 'Low')})</strong></p>
    </div>

    <div class="card">
        <h2>Recommendations</h2>
        <ul>
            {"".join([f"<li>{r}</li>" for r in recommendations])}
        </ul>
    </div>
</body>
</html>"""
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(html_content)

    elif format_type == "md":
        md_content = f"""# {title}
*Generated by SurveySnap AI Engine on {datetime.datetime.now().strftime('%Y-%m-%d')}*

---

## 1. Executive Summary
- **Total Records:** {summary.get('total_records', 0)}
- **Total Fields:** {summary.get('total_columns', 0)}
- **Data Quality:** {100 - summary.get('missing_percentage', 0)}% complete

## 2. Risk Assessment
- **Risk Score:** {risk.get('score', 0)}/100 ({risk.get('level', 'Low')} Risk)

## 3. Strategic Recommendations
{"".join([f"- {r}\n" for r in recommendations])}
"""
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(md_content)

    return file_path

def generate_executive_report(db: Session, file_id: int, title: str = "Executive Report", format_type: str = "pdf") -> Dict[str, Any]:
    from backend.services.analytics_service import generate_file_analytics
    analytics = generate_file_analytics(db, file_id)
    out_path = generate_report(title, analytics, str(REPORTS_DIR), format_type)
    return {"message": "Report generated", "report_path": out_path}
