import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(const SmartKumbhApp());
}

// Global ValueNotifier to manage active language across the entire application
final ValueNotifier<String> appLanguageNotifier = ValueNotifier<String>('English');

// Comprehensive Translation Map for English, Hindi, and Marathi
final Map<String, Map<String, String>> localizedStrings = {
  'English': {
    'app_title': 'Smart Kumbh',
    'app_subtitle': 'Your Digital Companion',
    'register_btn': 'Register',
    'login_btn': 'LOGIN',
    'forget_password': 'Forget Password !?',
    'emergency_btn': 'Emergency Contact !',
    'welcome_register': 'Welcome',
    'welcome_login': 'Welcome Again !',
    'full_name': 'Full Name:',
    'email': 'E.Mail:',
    'contact_no': 'Contact No',
    'personal': '(Personal)',
    'address': 'Address:',
    'kumbha_id': 'Kumbha Id:',
    'password': 'Password:',
    'click_to_continue': 'Click To Continue',
    'circle_tracker_title': 'My Circle Tracker',
    'band_id_sub': '(WB12345)',
    'enter_id': 'Enter ID:',
    'mention_band': '(Mention Below The Band)',
    'add_to_circle': 'Add To Circle',
    'connected_peoples': 'Connected Peoples:',
    'location_label': 'Location:',
    'km_away': 'km away',
    'directions': 'Directions',
    'sos_ring': 'SOS Ring',
    'mini_map_preview': '[Mini Map Preview with pins for Connected Users]',
    'offline_maps_title': 'Welcome To Offline\nMaps',
    'find_location': '📍 Find Your Loction',
    'go_back': 'Go Back',
    'crowd_density_title': 'Crowd Density',
    'live_heat_map': 'Live Heat Map !',
    'real_time_crowd': 'Real Time Crowd',
    'new_suggested_route': 'New Suggested Route',
    'lost_person_title': 'AI Lost Person\nFinder',
    'upload_recent_photo': 'Upload a Recent Photo:',
    'take_photo': 'Take Photo',
    'import_btn': 'Import',
    'preview_btn': 'Preview',
    'enter_description': 'Enter Description:',
    'label_name': 'Name:',
    'label_clothing': 'Clothing:',
    'label_last_seen_loc': 'Last Seen Location:',
    'select_on_map': '[ Select on Map ]',
    'label_last_seen_time': 'Last Seen Time:',
    'search_using_ai': 'Search Using AI',
    'possible_matches': 'Possible Matches:',
    'match_1': 'Match (85%) - Sector 4, Gate 3, 11:45 AM',
    'match_2': 'Match (72%) - Sector 7, Main Road, 11:30 AM',
    'view_details': '[ View Details ]',
    'alert_volunteers': 'Alert Volunteers',
    'traffic_title': 'Smart Traffic\nController',
    'traffic_subtitle': '(Signal 1 - MG Road)',
    'traffic_density_label': 'Traffic Density:',
    'north_density': 'North: 45',
    'south_density': 'South: 12',
    'east_density': 'East: 33',
    'west_density': 'West: 20',
    'current_light_label': 'Current Light:',
    'north_dir': 'North',
    'timer_label': 'Timer: 25s',
    'logs_label': 'Logs:',
    'log_1': '[11:02] North released (45 cars)..',
    'log_2': '[11:05] East released (33 cars)..',
    'log_3': '[11.30] West released (20 cars)..',
    'log_4': '[12.00] South released (12 cars)..',
    'lang_translator_title': 'Language Help &\nTranslator',
    'select_lang_label': 'Select Language:',
    'quick_phrases': 'Quick Phrases:',
    'phrase_1': 'Where is the nearest toilet?',
    'phrase_2': 'How do I reach Gate 5?',
    'phrase_3': 'Please call medical help.',
    'phrase_4': 'I am lost, please help me.',
    'realtime_translator': 'Real-Time Translator',
    'speak_btn': 'Speak',
    'autodetect_btn': 'Auto-Detect (Tamil)',
    'output_text_1': 'Output: "Please help me,\nI am lost"',
    'play_btn': 'Play',
    'voice_assistant': 'Voice Assistant :',
    'microphone_btn': 'Microphone',
    'say_prompt': 'Say: “Where is parking?”',
    'output_text_2': 'Output: “Nearest parking is\n200m ahead.”',
    'live_announcement_title': 'Live\nAnnouncement !!',
    'notification_label': 'Notification!',
    'urgent_alert_title': '🚨 URGENT ALERT',
    'urgent_alert_msg': 'Avoid XYZ Ghat – heavy crowd reported.',
    'urgent_alert_time': '[ 11:45 AM ]',
    'recent_alerts_title': 'Recent Alerts:',
    'recent_alert_1': '🔔 Procession starting in 10 mins (Sector 4) [11:30]',
    'recent_alert_2': '⚠️ Avoid ABC Road – too crowded [11:15]',
    'recent_alert_3': '🚨 Child lost, Info Booth #5 [11:05]',
    'filters_btn': 'Filters:',
    'safety_btn': 'Safety',
    'info_btn': 'Info',
    'events_btn': 'Events',
    'cleanliness_title': 'Cleanliness & Waste\nManagement',
    'nearby_services': 'Nearby Services:',
    'service_dustbin': 'Dustbin – 120m away',
    'service_toilet': 'Toilet – 300m away',
    'service_cleaning': 'Cleaning Booth – 50m',
    'navigate_btn': 'Navigate',
    'report_cleaning': '! Report Area Needs Cleaning',
    'geo_camera': 'Geo Camera 📷',
    'upload_btn': 'Upload',
    'clean_tip_title': 'Clean Tip:',
    'clean_tip_msg': '"Please use dustbins to keep the\nghats clean."',
    'disaster_title': 'Disaster\nManagement',
    'fire_emergency': 'Fire Emergency',
    'loc_sector_12': 'Location: Sector 12, Building A',
    'status_fire': 'Status: Active Fire Detected',
    'risk_high': 'People at Risk: High (120+)',
    'eta_fire': 'Response ETA: 8 mins',
    'flood_alert': 'Flood Alert',
    'loc_riverfront': 'Location: Riverfront Zone, Gate 3',
    'status_flood': 'Status: Rising Water Level',
    'people_affected': 'People Affected: Medium (60+)',
    'eta_flood': 'Safe Zone ETA: 15 mins',
    'risk_heatmap': 'Risk Heatmap on Your Location',
    'status_safe': 'Safe',
    'status_mod': 'Mod',
    'status_danger': 'Danger',
    'alerts_notif_title': 'Alerts & Notifications',
    'alert_fire_sector12': 'Fire in Sector 12',
    'alert_flood_riverfront': 'Flood near Riverfront',
    'alert_leakage_sector5': 'Major Leakage in Sector 5',
    'parking_guidance_title': 'Smart Parking\nGuidance',
    'parking_lot_a': 'Parking Lot A - 1.5 km away',
    'status_available': 'Status:  ✅  Available (80/200 slots)',
    'navigate_to_parking': 'Navigate to Parking',
    'parking_lot_b': 'Parking Lot B - 2.3 km away',
    'status_limited': 'Status:  ⚠️  Limited (190/200 slots)',
    'parking_lot_c': 'Parking Lot C - 3.0 km away',
    'status_full': 'Status:  ❌  Full',
    'notify_when_available': 'Notify When Available',
    'route_from_to': 'From Parking Lot A ➔ Nearest Entry Gate #4',
    'show_walking_route': 'Show Walking Route',
    'bus_control_title': 'Bus Control',
    'search_bus_route': 'Search Bus / Route:',
    'search_btn': 'Search',
    'live_bus_overview': 'Live Bus Overview',
    'bus_101_route': '[ Bus #101 – Route A ➔ Gate 3 ]',
    'loc_stop_12': 'Location: Near Stop 12 (2.3 km)',
    'crowd_high': 'Crowd Density:  ⚠️  High (80%)',
    'eta_gate_12': 'ETA to Gate: 12 mins',
    'track_live': 'Track Live',
    'send_alert': 'Send Alert',
    'bus_205_route': '[ Bus #205 – Route B ➔ Gate 7 ]',
    'loc_stop_4': 'Location: Near Stop 4 (1.1 km)',
    'crowd_nom': 'Crowd Density:  ✅  Nom (40%)',
    'eta_gate_7': 'ETA to Gate: 7 mins',
    'bus_101_overcrowded': 'Bus #101 overcrowded',
    'route_b_blocked': 'Route B blocked',
    'emergency_medical_title': 'Emergency\nMedical Service',
    'sos_subtitle': 'Click If Serious Medical Emergency',
    'nearby_hospitals': 'Nearby Hospitals\n& Clinics',
    'first_aid_team': 'First Aid Team',
    'call_to_ambulance': 'Call To\nAmubulance',
    'call_btn': 'Call',
    'todays_event_title': 'Todays Event !',
    'event_morning_aarti': 'Morning Aarti (7:30am)',
    'event_holy_dip': 'Holy Dip Ceremony',
    'event_evening_aarti': 'Evening Aarti (7:00pm)',
    'event_shahi_snan': 'Shahi Snan (4:00am)',
    'event_religious_discourses': 'Religious Discourses',
    'event_havan_ceremonies': 'Havan Ceremonies',
    'venue_btn': 'Venue 📍',
    'direction_btn': 'Direction',
    'smart_puja_title': 'Smart Puja 🪔',
    'book_puja_online': '"Book Your Puja Online"',
    'enter_description_puja': 'Enter Description',
    'full_name_puja': 'Full Name:',
    'mobile_number': 'Mobile Number:',
    'venue_puja': 'Venue :',
    'choose_time': 'Choose Time:',
    'pick_time': 'Pick Time:',
    'no_of_people': 'No. of People:',
    'select_dropdown': 'Select ▼',
    'choose_date': 'Choose Date:',
    'pick_date': 'Pick Date:',
    'select_puja_type': '🙏 Select Puja Type: ▼',
    'confirm_booking': 'Confirm Booking',
    'booked_puja': 'Booked Puja 🪔',
    'puja_name_val': 'Puja Name: Rudrabhishek',
    'date_val': 'Date: 20th February 2027',
    'time_val': 'Time: 10:30 AM',
    'venue_val': 'Venue: XYZ Sangham',
    'info_booths_title': 'Info Booths',
    'head_booth': 'Head Booth',
    'click_to_contact_head': 'Click To Contact\nHead Booth',
    'click_to_search_nearest': 'Click To Search\nNearest Booth To You!',
    'hotel_management_title': 'Hotel Management',
    'click_to_search_nearest_hotel': 'Click To Search\nNearest Hotel',
    'click_to_order_food_online': 'Click To Order\nFood Online',
    'click_to_contact_emergency_food': 'Click To Contact\nEmergency Food\nService Station',
    'ambulace_btn': 'Ambulace 🚑',
    'police_btn': 'Police 👮',
    'info_booths_btn': 'Info Booths',
    'medical_team_btn': 'Medical Team 🩺',
    'report_a_problem_title': 'Report a Problem',
    'if_you_face_issue': 'If you face any issue during the Mela',
    'chat_with_volunteers': 'Chat with Volunteers',
    'start_chat_now': '[ Start Chat Now ]',
    'how_to_use_guide': 'How to Use This App (Guide)',
    'small_tutorial_text': 'Small step-by-step tutorial\nwith visuals/icons:',
    'report_issues_text': '“Report issues for help and\nsolutions.”',
    'rating_title': 'Rating !',
    'profile_info': 'Profile Info',
    'home_page_menu': '> Home Page',
    'login_page_menu': '> Login Page',
    'my_circle_tracker_menu': '> My Circle Tracker',
    'offline_maps_menu': '> Offline Maps',
    'live_heat_map_menu': '> Live Heat Map',
    'ai_lost_finder_menu': '> AI Lost Finder',
    'smart_traffic_menu': '> Smart Traffic',
    'language_help_menu': '> Language Help',
    'live_announcement_menu': '> Live Announcement',
    'cleanliness_management_menu': '> Cleanliness Management',
    'disaster_management_menu': '> Disaster Management',
    'smart_parking_menu': '> Smart Parking',
    'bus_control_menu': '> Bus Control',
    'medical_emergency_menu': '> Medical Emergency',
    'todays_event_menu': '> Today\'s Event',
    'smart_puja_menu': '> Smart Puja',
    'info_booth_menu': '> Info Booth',
    'hotel_management_menu': '> Hotel Management',
    'sos_menu': '> SOS',
    'help_disk_menu': '> Help Disk',
    'exit_btn': 'Exit',
    'home_btn_tooltip': 'Go to Home Page',
  },
  'Hindi': {
    'app_title': 'स्मार्ट कुंभ',
    'app_subtitle': 'आपका डिजिटल साथी',
    'register_btn': 'पंजीकरण',
    'login_btn': 'लॉगिन',
    'forget_password': 'पासवर्ड भूल गए !?',
    'emergency_btn': 'आपातकालीन संपर्क !',
    'welcome_register': 'स्वागत हे',
    'welcome_login': 'फिर से स्वागत हे !',
    'full_name': 'पूरा नाम:',
    'email': 'ई-मेल:',
    'contact_no': 'संपर्क नंबर',
    'personal': '(व्यक्तिगत)',
    'address': 'पता:',
    'kumbha_id': 'कुंभ आईडी:',
    'password': 'पासवर्ड:',
    'click_to_continue': 'आगे बढ़ने के लिए क्लिक करें',
    'circle_tracker_title': 'मेरा सर्कल ट्रैकर',
    'band_id_sub': '(WB12345)',
    'enter_id': 'आईडी दर्ज करें:',
    'mention_band': '(बैंड के नीचे उल्लेखित)',
    'add_to_circle': 'सर्कल में जोड़ें',
    'connected_peoples': 'जुड़े हुए लोग:',
    'location_label': 'स्थान:',
    'km_away': 'किमी दूर',
    'directions': 'दिशा-निर्देश',
    'sos_ring': 'एसओएस रिंग',
    'mini_map_preview': '[जुड़े उपयोगकर्ताओं के पिन के साथ मिनी मैप पूर्वावलोकन]',
    'offline_maps_title': 'ऑफलाइन नक्शों में आपका\nस्वागत है',
    'find_location': '📍 अपना स्थान खोजें',
    'go_back': 'वापस जाएँ',
    'crowd_density_title': 'भीड़ का घनत्व',
    'live_heat_map': 'लाइव हीट मैप !',
    'real_time_crowd': 'रियल टाइम भीड़',
    'new_suggested_route': 'नया सुझाया गया मार्ग',
    'lost_person_title': 'एआई खोया व्यक्ति\nखोजक',
    'upload_recent_photo': 'हाल का फोटो अपलोड करें:',
    'take_photo': 'फोटो लें',
    'import_btn': 'इम्पोर्ट करें',
    'preview_btn': 'पूर्वावलोकन',
    'enter_description': 'विवरण दर्ज करें:',
    'label_name': 'नाम:',
    'label_clothing': 'कपड़े:',
    'label_last_seen_loc': 'अंतिम देखा गया स्थान:',
    'select_on_map': '[ नक्शे पर चुनें ]',
    'label_last_seen_time': 'अंतिम देखा गया समय:',
    'search_using_ai': 'एआई का उपयोग करके खोजें',
    'possible_matches': 'संभावित मिलान:',
    'match_1': 'मिलान (85%) - सेक्टर 4, गेट 3, 11:45 AM',
    'match_2': 'मिलान (72%) - सेक्टर 7, मुख्य सड़क, 11:30 AM',
    'view_details': '[ विवरण देखें ]',
    'alert_volunteers': 'स्वयंसेवकों को अलर्ट करें',
    'traffic_title': 'स्मार्ट ट्रैफिक\nकंट्रोलर',
    'traffic_subtitle': '(सिग्नल 1 - एमजी रोड)',
    'traffic_density_label': 'ट्रैफिक घनत्व:',
    'north_density': 'उत्तर: 45',
    'south_density': 'दक्षिण: 12',
    'east_density': 'पूर्व: 33',
    'west_density': 'पश्चिम: 20',
    'current_light_label': 'वर्तमान लाइट:',
    'north_dir': 'उत्तर',
    'timer_label': 'टाइमर: 25s',
    'logs_label': 'लॉग्स:',
    'log_1': '[11:02] उत्तर छोड़ा गया (45 कारें)..',
    'log_2': '[11:05] पूर्व छोड़ा गया (33 कारें)..',
    'log_3': '[11.30] पश्चिम छोड़ा गया (20 कारें)..',
    'log_4': '[12.00] दक्षिण छोड़ा गया (12 कारें)..',
    'lang_translator_title': 'भाषा सहायता एवं\nअनुवादक',
    'select_lang_label': 'भाषा चुनें:',
    'quick_phrases': 'त्वरित वाक्यांश:',
    'phrase_1': 'निकटतम शौचालय कहाँ है?',
    'phrase_2': 'मैं गेट 5 तक कैसे पहुँचूँ?',
    'phrase_3': 'कृपया चिकित्सा सहायता बुलाएं।',
    'phrase_4': 'मैं खो गया हूँ, कृपया मेरी मदद करें।',
    'realtime_translator': 'रियल-टाइम अनुवादक',
    'speak_btn': 'बोलें',
    'autodetect_btn': 'ऑटो-डिटेक्ट (तमिल)',
    'output_text_1': 'आउटपुट: "कृपया मेरी मदद करें,\nमैं खो गया हूँ"',
    'play_btn': 'चलाएं',
    'voice_assistant': 'वॉयस असिस्टेंट :',
    'microphone_btn': 'माइक्रोफोन',
    'say_prompt': 'बोलें: “पार्विंग कहाँ है?”',
    'output_text_2': 'आउटपुट: “निकटतम पार्किंग\n200 मीटर आगे है।”',
    'live_announcement_title': 'लाइव\nघोषणा !!',
    'notification_label': 'अधिसूचना!',
    'urgent_alert_title': '🚨 तत्काल अलर्ट',
    'urgent_alert_msg': 'एक्सवाईजेड घाट से बचें - भारी भीड़ दर्ज की गई।',
    'urgent_alert_time': '[ 11:45 AM ]',
    'recent_alerts_title': 'हाल के अलर्ट:',
    'recent_alert_1': '🔔 जुलूस 10 मिनट में शुरू (सेक्टर 4) [11:30]',
    'recent_alert_2': '⚠️ एबीसी रोड से बचें - बहुत भीड़ [11:15]',
    'recent_alert_3': '🚨 बच्चा खो गया, सूचना बूथ #5 [11:05]',
    'filters_btn': 'फ़िल्टर:',
    'safety_btn': 'सुरक्षा',
    'info_btn': 'सूचना',
    'events_btn': 'कार्यक्रम',
    'cleanliness_title': 'स्वच्छता एवं कचरा\nप्रबंधन',
    'nearby_services': 'पास की सेवाएं:',
    'service_dustbin': 'कूड़ेदान – 120m दूर',
    'service_toilet': 'शौचालय – 300m दूर',
    'service_cleaning': 'सफाई बूथ – 50m',
    'navigate_btn': 'नेविगेट',
    'report_cleaning': '! क्षेत्र की सफाई की आवश्यकता की रिपोर्ट करें',
    'geo_camera': 'जियो कैमरा 📷',
    'upload_btn': 'अपलोड करें',
    'clean_tip_title': 'स्वच्छता सुझाव:',
    'clean_tip_msg': '"घाटों को साफ रखने के लिए\nकृपया कूड़ेदान का उपयोग करें।"',
    'disaster_title': 'आपदा\nप्रबंधन',
    'fire_emergency': 'आग की आपातस्थिति',
    'loc_sector_12': 'स्थान: सेक्टर 12, बिल्डिंग ए',
    'status_fire': 'स्थिति: सक्रिय आग का पता चला',
    'risk_high': 'जोखिम में लोग: उच्च (120+)',
    'eta_fire': 'प्रतिक्रिया ईटीए: 8 मिनट',
    'flood_alert': 'बाढ़ अलर्ट',
    'loc_riverfront': 'स्थान: रिवरफ्रंट ज़ोन, गेट 3',
    'status_flood': 'स्थिति: जल स्तर बढ़ रहा है',
    'people_affected': 'प्रभावित लोग: मध्यम (60+)',
    'eta_flood': 'सुरक्षित क्षेत्र ईटीए: 15 मिनट',
    'risk_heatmap': 'आपके स्थान पर जोखिम हीटमैप',
    'status_safe': 'सुरक्षित',
    'status_mod': 'मध्यम',
    'status_danger': 'खतरा',
    'alerts_notif_title': 'अलर्ट और सूचनाएं',
    'alert_fire_sector12': 'सेक्टर 12 में आग',
    'alert_flood_riverfront': 'रिवरफ्रंट के पास बाढ़',
    'alert_leakage_sector5': 'सेक्टर 5 में बड़ा रिसाव',
    'parking_guidance_title': 'स्मार्ट पार्किंग\nमार्गदर्शन',
    'parking_lot_a': 'पार्किंग लॉट ए - 1.5 किमी दूर',
    'status_available': 'स्थिति:  ✅  उपलब्ध (80/200 स्लॉट)',
    'navigate_to_parking': 'पार्किंग के लिए नेविगेट करें',
    'parking_lot_b': 'पार्किंग लॉट बी - 2.3 किमी दूर',
    'status_limited': 'स्थिति:  ⚠️  सीमित (190/200 स्लॉट)',
    'parking_lot_c': 'पार्किंग लॉट सी - 3.0 किमी दूर',
    'status_full': 'स्थिति:  ❌  पूर्ण',
    'notify_when_available': 'उपलब्ध होने पर सूचित करें',
    'route_from_to': 'पार्किंग लॉट ए ➔ निकटतम प्रवेश द्वार #4 से',
    'show_walking_route': 'पैदल चलने का मार्ग दिखाएं',
    'bus_control_title': 'बस नियंत्रण',
    'search_bus_route': 'बस / मार्ग खोजें:',
    'search_btn': 'खोजें',
    'live_bus_overview': 'लाइव बस अवलोकन',
    'bus_101_route': '[ बस #101 – रूट ए ➔ गेट 3 ]',
    'loc_stop_12': 'स्थान: स्टॉप 12 के पास (2.3 किमी)',
    'crowd_high': 'भीड़ घनत्व:  ⚠️  उच्च (80%)',
    'eta_gate_12': 'गेट का ईटीए: 12 मिनट',
    'track_live': 'लाइव ट्रैक करें',
    'send_alert': 'अलर्ट भेजें',
    'bus_205_route': '[ बस #205 – रूट बी ➔ गेट 7 ]',
    'loc_stop_4': 'स्थान: स्टॉप 4 के पास (1.1 किमी)',
    'crowd_nom': 'भीड़ घनत्व:  ✅  सामान्य (40%)',
    'eta_gate_7': 'गेट का ईटीए: 7 मिनट',
    'bus_101_overcrowded': 'बस #101 में अत्यधिक भीड़',
    'route_b_blocked': 'रूट बी अवरुद्ध',
    'emergency_medical_title': 'आपातकालीन\nचिकित्सा सेवा',
    'sos_subtitle': 'गंभीर चिकित्सा आपातस्थिति होने पर क्लिक करें',
    'nearby_hospitals': 'पास के अस्पताल\nऔर क्लीनिक',
    'first_aid_team': 'प्राथमिक उपचार टीम',
    'call_to_ambulance': 'एम्बुलेंस को\nकॉल करें',
    'call_btn': 'कॉल करें',
    'todays_event_title': 'आज के कार्यक्रम !',
    'event_morning_aarti': 'प्रातः आरती (7:30am)',
    'event_holy_dip': 'पवित्र स्नान समारोह',
    'event_evening_aarti': 'संध्या आरती (7:00pm)',
    'event_shahi_snan': 'शाही स्नान (4:00am)',
    'event_religious_discourses': 'धार्मिक प्रवचन',
    'event_havan_ceremonies': 'हवन समारोह',
    'venue_btn': 'स्थान 📍',
    'direction_btn': 'दिशा',
    'smart_puja_title': 'स्मार्ट पूजा 🪔',
    'book_puja_online': '"ऑनलाइन अपनी पूजा बुक करें"',
    'enter_description_puja': 'विवरण दर्ज करें',
    'full_name_puja': 'पूरा नाम:',
    'mobile_number': 'मोबाइल नंबर:',
    'venue_puja': 'स्थान :',
    'choose_time': 'समय चुनें:',
    'pick_time': 'समय चुनें:',
    'no_of_people': 'लोगों की संख्या:',
    'select_dropdown': 'चुनें ▼',
    'choose_date': 'तारीख चुनें:',
    'pick_date': 'तारीख चुनें:',
    'select_puja_type': '🙏 पूजा का प्रकार चुनें: ▼',
    'confirm_booking': 'बुकिंग की पुष्टि करें',
    'booked_puja': 'बुक की गई पूजा 🪔',
    'puja_name_val': 'पूजा का नाम: रुद्राभिषेक',
    'date_val': 'तारीख: 20 फरवरी 2027',
    'time_val': 'समय: 10:30 AM',
    'venue_val': 'स्थान: एक्सवाईजेड संघम',
    'info_booths_title': 'सूचना बूथ',
    'head_booth': 'मुख्य बूथ',
    'click_to_contact_head': 'मुख्य बूथ से संपर्क करने\nके लिए क्लिक करें',
    'click_to_search_nearest': 'अपने निकटतम बूथ को\nखोजने के लिए क्लिक करें!',
    'hotel_management_title': 'होटल प्रबंधन',
    'click_to_search_nearest_hotel': 'निकटतम होटल खोजने\nके लिए क्लिक करें',
    'click_to_order_food_online': 'ऑनलाइन खाना ऑर्डर\nकरने के लिए क्लिक करें',
    'click_to_contact_emergency_food': 'आपातकालीन खाद्य सेवा\nस्टेशन से संपर्क करने\nके लिए क्लिक करें',
    'ambulace_btn': 'एम्बुलेंस 🚑',
    'police_btn': 'पुलिस 👮',
    'info_booths_btn': 'सूचना बूथ',
    'medical_team_btn': 'चिकित्सा दल 🩺',
    'report_a_problem_title': 'समस्या की रिपोर्ट करें',
    'if_you_face_issue': 'यदि मेले के दौरान आपको कोई समस्या आती है',
    'chat_with_volunteers': 'स्वयंसेवकों के साथ चैट करें',
    'start_chat_now': '[ अब चैट शुरू करें ]',
    'how_to_use_guide': 'इस ऐप का उपयोग कैसे करें (गाइड)',
    'small_tutorial_text': 'दृश्य/आइकन के साथ\nछोटा चरण-दर-चरण ट्यूटोरियल:',
    'report_issues_text': '“मदद और समाधान के लिए\nमुद्दों की रिपोर्ट करें।”',
    'rating_title': 'रेटिंग !',
    'profile_info': 'प्रोफाइल जानकारी',
    'home_page_menu': '> होम पेज',
    'login_page_menu': '> लॉगिन पेज',
    'my_circle_tracker_menu': '> माय सर्कल ट्रैकर',
    'offline_maps_menu': '> ऑफलाईन नकाशे',
    'live_heat_map_menu': '> लाइव हीट मैप',
    'ai_lost_finder_menu': '> एआई खोया व्यक्ति',
    'smart_traffic_menu': '> स्मार्ट ट्रैफिक',
    'language_help_menu': '> भाषा सहायता',
    'live_announcement_menu': '> लाइव घोषणा',
    'cleanliness_management_menu': '> स्वच्छता प्रबंधन',
    'disaster_management_menu': '> आपदा प्रबंधन',
    'smart_parking_menu': '> स्मार्ट पार्किंग',
    'bus_control_menu': '> बस नियंत्रण',
    'medical_emergency_menu': '> चिकित्सा आपात स्थिति',
    'todays_event_menu': '> आज के कार्यक्रम',
    'smart_puja_menu': '> स्मार्ट पूजा',
    'info_booth_menu': '> सूचना बूथ',
    'hotel_management_menu': '> होटल प्रबंधन',
    'sos_menu': '> एसओएस',
    'help_disk_menu': '> हेल्प डेस्क',
    'exit_btn': 'बाहर निकलें',
    'home_btn_tooltip': 'होम पेज पर जाएं',
  },
  'Marathi': {
    'app_title': 'स्मार्ट कुंभ',
    'app_subtitle': 'आपला डिजिटल साथी',
    'register_btn': 'नोंदणी',
    'login_btn': 'लॉगिन',
    'forget_password': 'पासवर्ड विसरलात !?',
    'emergency_btn': 'आपत्कालीन संपर्क !',
    'welcome_register': 'स्वागत आहे',
    'welcome_login': 'पुन्हा स्वागत आहे !',
    'full_name': 'पूर्ण नाव:',
    'email': 'ई-मेल:',
    'contact_no': 'संपर्क क्रमांक',
    'personal': '(वैयक्तिक)',
    'address': 'पत्ता:',
    'kumbha_id': 'कुंभ आयडी:',
    'password': 'पासवर्ड:',
    'click_to_continue': 'पुढे जाण्यासाठी क्लिक करा',
    'circle_tracker_title': 'माझे सर्कल ट्रॅकर',
    'band_id_sub': '(WB12345)',
    'enter_id': 'आयडी प्रविष्ट करा:',
    'mention_band': '(बँडच्या खाली नमूद केलेले)',
    'add_to_circle': 'सर्कलमध्ये जोडा',
    'connected_peoples': 'जोडलेले लोक:',
    'location_label': 'स्थान:',
    'km_away': 'किमी लांब',
    'directions': 'दिशा-निर्देश',
    'sos_ring': 'एसओएस रिंग',
    'mini_map_preview': '[जोडलेल्या वापरकर्त्यांसाठी पिनसह मिनी मॅप पूर्वावलोकन]',
    'offline_maps_title': 'ऑफलाइन नकाशे मध्ये\nआपले स्वागत आहे',
    'find_location': '📍 तुमचे स्थान शोधा',
    'go_back': 'मागे जा',
    'crowd_density_title': 'गर्दीची घनता',
    'live_heat_map': 'लाइव्ह हीट मॅप !',
    'real_time_crowd': 'रिअल टाइम गर्दी',
    'new_suggested_route': 'नवीन सुचवलेला मार्ग',
    'lost_person_title': 'एआई हरवलेली व्यक्ती\nशोधक',
    'upload_recent_photo': 'अलीकडील फोटो अपलोड करा:',
    'take_photo': 'फोटो घ्या',
    'import_btn': 'इम्पोर्ट करा',
    'preview_btn': 'पूर्वावलोकन',
    'enter_description': 'वर्णन प्रविष्ट करा:',
    'label_name': 'नाव:',
    'label_clothing': 'कपडे:',
    'label_last_seen_loc': 'शेवटचे पाहिलेले स्थान:',
    'select_on_map': '[ नकाशावर निवडा ]',
    'label_last_seen_time': 'शेवटची वेळ:',
    'search_using_ai': 'एआय वापरून शोधा',
    'possible_matches': 'संभाव्य सामने:',
    'match_1': 'सामना (85%) - सेक्टर 4, गेट 3, 11:45 AM',
    'match_2': 'सामना (72%) - सेक्टर 7, मुख्य रस्ता, 11:30 AM',
    'view_details': '[ विवरण देखें ]',
    'alert_volunteers': 'स्वयंसेवकांना इशारा द्या',
    'traffic_title': 'स्मार्ट ट्रॅफिक\nकंट्रोलर',
    'traffic_subtitle': '(सिग्नल 1 - एमजी रोड)',
    'traffic_density_label': 'ट्रॅफिक घनता:',
    'north_density': 'उत्तर: 45',
    'south_density': 'दक्षिण: 12',
    'east_density': 'पूर्व: 33',
    'west_density': 'पश्चिम: 20',
    'current_light_label': 'सध्याचा दिवा:',
    'north_dir': 'उत्तर',
    'timer_label': 'टायमर: 25s',
    'logs_label': 'लॉग्स:',
    'log_1': '[11:02] उत्तर सोडले (45 गाड्या)..',
    'log_2': '[11:05] पूर्व सोडले (33 गाड्या)..',
    'log_3': '[11.30] पश्चिम सोडले (20 गाड्या)..',
    'log_4': '[12.00] दक्षिण सोडले (12 गाड्या)..',
    'lang_translator_title': 'भाषा मदत आणि\nभाषांतरकार',
    'select_lang_label': 'भाषा निवडा:',
    'quick_phrases': 'जलद वाक्ये:',
    'phrase_1': 'जवळचे शौचालय कोठे आहे?',
    'phrase_2': 'मी गेट 5 वर कसा पोहोचू?',
    'phrase_3': 'कृपया वैद्यकीय मदत बोलवा.',
    'phrase_4': 'मी हरवलो आहे, कृपया मला मदत करा.',
    'realtime_translator': 'रिअल-टाइम भाषांतरकार',
    'speak_btn': 'बोला',
    'autodetect_btn': 'ऑटो-डिटेक्ट (तमिळ)',
    'output_text_1': 'आउटपुट: "कृपया मला मदत करा,\nमी हरवलो आहे"',
    'play_btn': 'प्ले',
    'voice_assistant': 'व्हॉइस असिस्टंट :',
    'microphone_btn': 'मायक्रोफोन',
    'say_prompt': 'म्हणा: “पार्किंग कोठे आहे?”',
    'output_text_2': 'आउटपुट: “जवळचे पार्किंग\n200 मीटर पुढे आहे.”',
    'live_announcement_title': 'थेट\nजाहिरत !!',
    'notification_label': 'सूचना!',
    'urgent_alert_title': '🚨 तातडीचा इशारा',
    'urgent_alert_msg': 'एक्सवायझेड घाटावर जाणे टाळा – मोठी गर्दी झाली आहे.',
    'urgent_alert_time': '[ 11:45 AM ]',
    'recent_alerts_title': 'अलीकडील इशारे:',
    'recent_alert_1': '🔔 मिरवणूक 10 मिनिटांत सुरू (सेक्टर 4) [11:30]',
    'recent_alert_2': '⚠️ एबीसी रोड टाळा – खूप गर्दी [11:15]',
    'recent_alert_3': '🚨 मूल हरवले, माहिती बूथ #5 [11:05]',
    'filters_btn': 'फिल्टर्स:',
    'safety_btn': 'सुरक्षा',
    'info_btn': 'माहिती',
    'events_btn': 'कार्यक्रम',
    'cleanliness_title': 'स्वच्छता आणि कचरा\nव्यवस्थापन',
    'nearby_services': 'जवळपासच्या सेवा:',
    'service_dustbin': 'कचराकुंडी – 120m लांब',
    'service_toilet': 'शौचालय – 300m लांब',
    'service_cleaning': 'सफाई बूथ – 50m',
    'navigate_btn': 'नेव्हिगेट',
    'report_cleaning': '! परिसराची स्वच्छता करण्याची आवश्यकता नोंदवा',
    'geo_camera': 'जिओ कॅमेरा 📷',
    'upload_btn': 'अपलोड करा',
    'clean_tip_title': 'स्वच्छता टीप:',
    'clean_tip_msg': '"घाट स्वच्छ ठेवण्यासाठी कृपया\nकचराकुंडीचा वापर करा."',
    'disaster_title': 'आपत्ती\nव्यवस्थापन',
    'fire_emergency': '🔥 आगीची आणीबाणी',
    'loc_sector_12': '📍 स्थान: सेक्टर 12, इमारत ए',
    'status_fire': '🚨 स्थिती: आग आढळली',
    'risk_high': '👥 धोक्यात असलेले लोक: जास्त (120+)',
    'eta_fire': '⏱️ प्रतिसाद ईटीए: 8 मिनिटे',
    'flood_alert': '🌊 पूर इशारा',
    'loc_riverfront': '📍 स्थान: रिव्हरफ्रंट झोन, गेट 3',
    'status_flood': '🚨 स्थिती: पाण्याची पातळी वाढत आहे',
    'people_affected': '👥 बाधित लोक: मध्यम (60+)',
    'eta_flood': '⏱️ सुरक्षित क्षेत्र ईटीए: 15 मिनिटे',
    'risk_heatmap': '📊 तुमच्या स्थानावरील धोका हीटमॅप',
    'status_safe': 'सुरक्षित',
    'status_mod': 'मध्यम',
    'status_danger': 'धोका',
    'alerts_notif_title': '🔔 इशारे आणि सूचना',
    'alert_fire_sector12': '⚠️ सेक्टर 12 मध्ये आग',
    'alert_flood_riverfront': '🌊 रिव्हरफ्रंटजवळ पूर',
    'alert_leakage_sector5': '💧 सेक्टर 5 मध्ये मोठी गळती',
    'parking_guidance_title': 'स्मार्ट पार्किंग\nमार्गदर्शन',
    'parking_lot_a': '🅿️ पार्किंग लॉट ए - 1.5 किमी लांब',
    'status_available': 'स्थिती: ✅ उपलब्ध (80/200 स्लॉट)',
    'navigate_to_parking': 'पार्किंगकडे नेव्हिगेट करा',
    'parking_lot_b': '🅿️ पार्किंग लॉट बी - 2.3 किमी लांब',
    'status_limited': 'स्थिती: ⚠️ मर्यादित (190/200 स्लॉट)',
    'parking_lot_c': '🅿️ पार्किंग लॉट सी - 3.0 किमी लांब',
    'status_full': 'स्थिती: ❌ पूर्ण',
    'notify_when_available': 'उपलब्ध झाल्यावर सूचित करा',
    'route_from_to': 'पार्किंग लॉट ए ➔ जवळचे प्रवेश द्वार #4 वरून',
    'show_walking_route': 'चालण्याचा मार्ग दाखवा',
    'bus_control_title': 'बस नियंत्रण',
    'search_bus_route': '🔍 बस / मार्ग शोधा:',
    'search_btn': 'शोधा',
    'live_bus_overview': '🚏 थेट बस विहंगावलोकन',
    'bus_101_route': '[ बस #101 – रूट ए ➔ गेट 3 ]',
    'loc_stop_12': 'स्थान: स्टॉप 12 जवळ (2.3 किमी)',
    'crowd_high': 'गर्दीची घनता:  ⚠️  जास्त (80%)',
    'eta_gate_12': 'गेटचे ईटीए: 12 मिनिटे',
    'bus_205_route': '[ बस #205 – रूट बी ➔ गेट 7 ]',
    'loc_stop_4': 'स्थान: स्टॉप 4 जवळ (1.1 किमी)',
    'crowd_nom': 'गर्दीची घनता:  ✅  सामान्य (40%)',
    'eta_gate_7': 'गेटचे ईटीए: 7 मिनिटे',
    'bus_101_overcrowded': '⚠️ बस #101 मध्ये जास्त गर्दी',
    'route_b_blocked': 'रूट बी बंद',
    'emergency_medical_title': 'आपत्कालीन\nवैद्यकीय सेवा',
    'sos_subtitle': 'गंभीर वैद्यकीय आणीबाणी असल्यास क्लिक करा',
    'nearby_hospitals': 'जवळपासची रुग्णालये\nआणि क्लिनिक',
    'first_aid_team': 'प्रथमोपचार टीम',
    call_to_ambulance: 'ॲम्बुलन्सला\nकॉल करा',
    'call_btn': 'कॉल करा',
    'todays_event_title': 'आजचे कार्यक्रम !',
    'event_morning_aarti': 'सकाळची आरती (7:30am)',
    'event_holy_dip': 'पवित्र स्नान सोहळा',
    'event_evening_aarti': 'संध्याकाळची आरती (7:00pm)',
    'event_shahi_snan': 'शाही स्नान (4:00am)',
    'event_religious_discourses': 'धार्मिक प्रवचन',
    'event_havan_ceremonies': 'हवन सोहळा',
    'venue_btn': 'ठिकाण 📍',
    'direction_btn': 'दिशा',
    'smart_puja_title': 'स्मार्ट पूजा 🪔',
    'book_puja_online': '"ऑनलाइन आपली पूजा बुक करा"',
    'enter_description_puja': 'वर्णन प्रविष्ट करा',
    'full_name_puja': '👤 पूर्ण नाव:',
    'mobile_number': '📱 मोबाईल नंबर:',
    'venue_puja': '📍 ठिकाण :',
    'choose_time': '⏰ वेळ निवडा:',
    'pick_time': 'वेळ निवडा:',
    'no_of_people': '👥 लोकांची संख्या:',
    'select_dropdown': 'निवडा ▼',
    'choose_date': '🗓️ दिनांक निवडा:',
    'pick_date': 'दिनांक निवडा:',
    'select_puja_type': '🙏 पूजेचा प्रकार निवडा: ▼',
    'confirm_booking': 'बुकिंगची पुष्टी करा',
    'booked_puja': 'बुक केलेली पूजा 🪔',
    'puja_name_val': 'पूजेचे नाव: रुद्राभिषेक',
    'date_val': 'दिनांक: 20 फेब्रुवारी 2027',
    'time_val': 'वेळ: 10:30 AM',
    'venue_val': 'ठिकाण: एक्सवायझेड संघम',
    'info_booths_title': 'माहिती बूथ',
    'head_booth': 'मुख्य बूथ',
    'click_contact_head': 'मुख्य बूथशी संपर्क साधण्यासाठी\nक्लिक करा',
    'click_search_nearest': 'आपल्या जवळील बूथ\nशोधण्यासाठी क्लिक करा!',
    'hotel_management_title': 'हॉटेल व्यवस्थापन',
    'click_search_nearest_hotel': 'जवळील हॉटेल शोधण्यासाठी\nक्लिक करा',
    'click_order_food_online': 'ऑनलाइन अन्न ऑर्डर\nकरण्यासाठी क्लिक करा',
    'click_contact_emergency_food': 'आपत्कालीन अन्न सेवा\nस्टेशनशी संपर्क साधण्यासाठी\nक्लिक करा',
    'ambulace_btn': 'ॲम्बुलन्स 🚑',
    'police_btn': 'पोलीस 👮',
    'info_booths_btn': 'माहिती बूथ',
    'medical_team_btn': 'वैद्यकीय टीम 🩺',
    'report_a_problem_title': 'समस्येची तक्रार करा',
    'if_you_face_issue': 'मेळ्यादरम्यान तुम्हाला काही समस्या आल्यास',
    'chat_with_volunteers': 'स्वयंसेवकांशी चॅट करा',
    'start_chat_now': '[ आता चॅट सुरू करा ]',
    'how_to_use_guide': 'हे ॲप कसे वापरावे (मार्गदर्शक)',
    'small_tutorial_text': 'चित्रे/आयकॉनसह\nलहान टप्प्याटप्प्याने ट्यूटोरियल:',
    'report_issues_text': '“मदत आणि समाधानासाठी\nसमस्यांची तक्रार करा.”',
    'rating_title': 'रेटिंग !',
    'profile_info': 'प्रोफाइल माहिती',
    'home_page_menu': '> होम पेज',
    'login_page_menu': '> लॉगिन पेज',
    'my_circle_tracker_menu': '> माझे सर्कल ट्रॅकर',
    'offline_maps_menu': '> ऑफलाईन नकाशे',
    'live_heat_map_menu': '> लाइव्ह हीट मॅप',
    'ai_lost_finder_menu': '> एआई हरवलेला शोधक',
    'smart_traffic_menu': '> स्मार्ट ट्रॅफिक',
    'language_help_menu': '> भाषा मदत',
    'live_announcement_menu': '> थेट जाहीरत',
    'cleanliness_management_menu': '> स्वच्छता व्यवस्थापन',
    'disaster_management_menu': '> आपत्ती व्यवस्थापन',
    'smart_parking_menu': '> स्मार्ट पार्किंग',
    'bus_control_menu': '> बस नियंत्रण',
    'medical_emergency_menu': '> वैद्यकीय आणीबाणी',
    'todays_event_menu': '> आजचे कार्यक्रम',
    'smart_puja_menu': '> स्मार्ट पूजा',
    'info_booth_menu': '> माहिती बूथ',
    'hotel_management_menu': '> हॉटेल व्यवस्थापन',
    'sos_menu': '> एसओएस',
    'help_disk_menu': '> हेल्प डेस्क',
    'exit_btn': 'बाहेर पडा',
    'home_btn_tooltip': 'होम पेजवर जा',
  },
};

String tr(String key) {
  final lang = appLanguageNotifier.value;
  return localizedStrings[lang]?[key] ?? localizedStrings['English']![key]!;
}

class SmartKumbhApp extends StatelessWidget {
  const SmartKumbhApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<String>(
      valueListenable: appLanguageNotifier,
      builder: (context, currentLang, child) {
        return MaterialApp(
          title: 'Smart Kumbh',
          debugShowCheckedModeBanner: false,
          scrollBehavior: const MaterialScrollBehavior().copyWith(
            scrollbars: false,
          ),
          theme: ThemeData(
            scaffoldBackgroundColor: const Color(0xFFDBE5FF),
            useMaterial3: true,
            textTheme: GoogleFonts.itimTextTheme(),
          ),
          home: const DashboardScreen(),
        );
      },
    );
  }
}

// ==========================================
// 0. DASHBOARD / NAVIGATION MENU SCREEN
// ==========================================
class DashboardScreen extends StatelessWidget {
  const DashboardScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFDBE5FF),
      body: SafeArea(
        child: Column(
          children: [
            // Top Navigation Bar with Home Button
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  IconButton(
                    icon: const Icon(Icons.home_rounded, color: Colors.black, size: 34),
                    tooltip: tr('home_btn_tooltip'),
                    onPressed: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (context) => const WelcomeScreen()),
                      );
                    },
                  ),
                  GestureDetector(
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (context) => const WelcomeScreen()),
                      );
                    },
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 6),
                      decoration: BoxDecoration(
                        color: const Color(0xFF1E399C),
                        borderRadius: BorderRadius.circular(20),
                      ),
                      child: Row(
                        children: [
                          const Icon(Icons.home, color: Color(0xFFFBE4CB), size: 20),
                          const SizedBox(width: 6),
                          Text(
                            'Home',
                            style: GoogleFonts.itim(
                              fontSize: 18,
                              fontWeight: FontWeight.bold,
                              color: const Color(0xFFFBE4CB),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),

            Expanded(
              child: ScrollConfiguration(
                behavior: ScrollConfiguration.of(context).copyWith(scrollbars: false),
                child: SingleChildScrollView(
                  physics: const BouncingScrollPhysics(),
                  padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 8.0),
                  child: Column(
                    crossAxisAlignment: CrossAlignment.center,
                    children: [
                      // User Profile Avatar Silhouette
                      Container(
                        width: 120,
                        height: 120,
                        decoration: const BoxDecoration(
                          color: Color(0xFFB0BACF),
                          shape: BoxShape.circle,
                        ),
                        child: const Center(
                          child: Icon(
                            Icons.person,
                            size: 80,
                            color: Color(0xFF7A869E),
                          ),
                        ),
                      ),

                      const SizedBox(height: 8),

                      Text(
                        tr('profile_info'),
                        style: GoogleFonts.itim(
                          fontSize: 22,
                          fontWeight: FontWeight.bold,
                          color: Colors.black,
                        ),
                      ),

                      const SizedBox(height: 20),

                      // Navigation Items List
                      _buildMenuItem(context, tr('home_page_menu'), const WelcomeScreen()),
                      _buildMenuItem(context, tr('login_page_menu'), const LoginScreen()),
                      _buildMenuItem(context, tr('my_circle_tracker_menu'), const CircleTrackerScreen()),
                      _buildMenuItem(context, tr('offline_maps_menu'), const OfflineMapsScreen()),
                      _buildMenuItem(context, tr('live_heat_map_menu'), const CrowdDensityScreen()),
                      _buildMenuItem(context, tr('ai_lost_finder_menu'), const LostPersonFinderScreen()),
                      _buildMenuItem(context, tr('smart_traffic_menu'), const TrafficControllerScreen()),
                      _buildMenuItem(context, tr('language_help_menu'), const LanguageTranslatorScreen()),
                      _buildMenuItem(context, tr('live_announcement_menu'), const LiveAnnouncementsScreen()),
                      _buildMenuItem(context, tr('cleanliness_management_menu'), const CleanlinessWasteScreen()),
                      _buildMenuItem(context, tr('disaster_management_menu'), const DisasterManagementScreen()),
                      _buildMenuItem(context, tr('smart_parking_menu'), const SmartParkingGuidanceScreen()),
                      _buildMenuItem(context, tr('bus_control_menu'), const BusControlScreen()),
                      _buildMenuItem(context, tr('medical_emergency_menu'), const EmergencyMedicalServiceScreen()),
                      _buildMenuItem(context, tr('todays_event_menu'), const TodaysEventsScreen()),
                      _buildMenuItem(context, tr('smart_puja_menu'), const SmartPujaScreen()),
                      _buildMenuItem(context, tr('info_booth_menu'), const InfoBoothsScreen()),
                      _buildMenuItem(context, tr('hotel_management_menu'), const HotelManagementScreen()),
                      _buildMenuItem(context, tr('sos_menu'), const EmergencyContactsScreen()),
                      _buildMenuItem(context, tr('help_disk_menu'), const ReportProblemScreen()),

                      const SizedBox(height: 28),

                      // Exit Button
                      SizedBox(
                        width: 140,
                        height: 44,
                        child: ElevatedButton(
                          onPressed: () {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(content: Text('Exiting Smart Kumbh App...')),
                            );
                          },
                          style: ElevatedButton.styleFrom(
                            backgroundColor: const Color(0xFF6E8EF5),
                            foregroundColor: Colors.black,
                            elevation: 0,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                          child: Text(
                            tr('exit_btn'),
                            style: GoogleFonts.itim(
                              fontSize: 22,
                              fontWeight: FontWeight.bold,
                              color: const Color(0xFF1D2947),
                            ),
                          ),
                        ),
                      ),

                      const SizedBox(height: 24),
                    ],
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildMenuItem(BuildContext context, String label, Widget targetScreen) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4.0),
      child: InkWell(
        onTap: () {
          Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => targetScreen),
          );
        },
        child: SizedBox(
          width: double.infinity,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 4.0),
            child: Text(
              label,
              style: GoogleFonts.itim(
                fontSize: 22,
                fontWeight: FontWeight.bold,
                color: Colors.black,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
