import { Pujari, Driver, Hotel, KumbhLocation } from '../types';

export class KumbhService {
  private pujaris: Pujari[] = [
    {
      id: 'pujari-1',
      name: 'Pandit Rameshwar Shastri',
      specialization: 'Godavari Mahasnan & Kalsarp Dosh Shanti',
      experienceYears: 24,
      rating: 4.9,
      reviewCount: 480,
      verificationBadge: 'Verified',
      languages: ['Hindi', 'Marathi', 'Sanskrit'],
      location: 'Ram Kund, Nashik',
      ghat: 'Ram Kund',
      priceRange: '₹1,100 – ₹2,500',
      phone: '+91 98220 12345',
      overallScore: 96,
      rank: 1,
      whyRecommended: ['✓ 24+ years experience at Ram Kund', '✓ Official Nashik Purohit Sangh Verified', '✓ Transparent ritual Dakshina'],
    },
    {
      id: 'pujari-2',
      name: 'Acharya Vidhyadhar Joshi',
      specialization: 'Pitri Tarpan & Narayan Nagbali Rituals',
      experienceYears: 19,
      rating: 4.8,
      reviewCount: 310,
      verificationBadge: 'Verified',
      languages: ['Hindi', 'Marathi', 'Gujarati'],
      location: 'Trimbakeshwar Ghat, Nashik',
      ghat: 'Trimbakeshwar Ghat',
      priceRange: '₹1,500 – ₹3,100',
      phone: '+91 94222 67890',
      overallScore: 94,
      rank: 2,
      whyRecommended: ['✓ Specialized in Vedic Snan & Tarpan', '✓ High family satisfaction rating', '✓ Direct contact available'],
    },
    {
      id: 'pujari-3',
      name: 'Shri Balkrishna Guruji',
      specialization: 'Family Sankalp & Snan Ritual Guidance',
      experienceYears: 16,
      rating: 4.8,
      reviewCount: 240,
      verificationBadge: 'Verified',
      languages: ['Hindi', 'English', 'Marathi'],
      location: 'Godavari Ghat, Panchavati',
      ghat: 'Godavari Ghat',
      priceRange: '₹750 – ₹1,800',
      phone: '+91 98901 34567',
      overallScore: 92,
      rank: 3,
      whyRecommended: ['✓ Excellent English & Hindi fluency', '✓ Great for elderly & family groups', '✓ Reasonable fair pricing'],
    },
    {
      id: 'pujari-4',
      name: 'Pandit Kedar Nath Tripathi',
      specialization: 'Rudra Abhishek & Maha Aarti',
      experienceYears: 22,
      rating: 4.7,
      reviewCount: 190,
      verificationBadge: 'Verified',
      languages: ['Hindi', 'Sanskrit'],
      location: 'Tapovan Ghat, Nashik',
      ghat: 'Tapovan Ghat',
      priceRange: '₹1,000 – ₹2,200',
      phone: '+91 97654 89012',
      overallScore: 90,
      rank: 4,
      whyRecommended: ['✓ Traditional Vedic Vidhi', '✓ Trusted by repeat pilgrimage groups'],
    },
    {
      id: 'pujari-5',
      name: 'Acharya Shrikant Kulkarni',
      specialization: 'Navgraha Shanti & Holy Bath Guidance',
      experienceYears: 14,
      rating: 4.7,
      reviewCount: 165,
      verificationBadge: 'Community Rated',
      languages: ['Marathi', 'Hindi'],
      location: 'Ram Kund, Nashik',
      ghat: 'Ram Kund',
      priceRange: '₹800 – ₹1,500',
      phone: '+91 94231 56789',
      overallScore: 88,
      rank: 5,
      whyRecommended: ['✓ High community rating', '✓ Patient guidance for first-time visitors'],
    },
    {
      id: 'pujari-6',
      name: 'Shri Vasudev Upadhyay',
      specialization: 'Godavari Snan & Deep Dan Ceremony',
      experienceYears: 12,
      rating: 4.6,
      reviewCount: 130,
      verificationBadge: 'Community Rated',
      languages: ['Hindi'],
      location: 'Godavari Ghat, Panchavati',
      ghat: 'Godavari Ghat',
      priceRange: '₹500 – ₹1,200',
      phone: '+91 98812 34567',
      overallScore: 86,
      rank: 6,
      whyRecommended: ['✓ Affordable traditional rites', '✓ Located right at main Ghat entrance'],
    },
    {
      id: 'pujari-7',
      name: 'Pandit Shivprasad Sharma',
      specialization: 'Ganga-Godavari Samagam Sankalp',
      experienceYears: 18,
      rating: 4.6,
      reviewCount: 145,
      verificationBadge: 'Verified',
      languages: ['Hindi', 'English'],
      location: 'Ram Kund, Nashik',
      ghat: 'Ram Kund',
      priceRange: '₹1,200 – ₹2,400',
      phone: '+91 93701 98765',
      overallScore: 85,
      rank: 7,
      whyRecommended: ['✓ Verified profile', '✓ Clear breakdown of ritual materials included'],
    },
    {
      id: 'pujari-8',
      name: 'Acharya Anand Dikshit',
      specialization: 'Chodi Puja & Family Ashirwad',
      experienceYears: 15,
      rating: 4.5,
      reviewCount: 110,
      verificationBadge: 'Official Source',
      languages: ['Marathi', 'Hindi'],
      location: 'Kalaram Temple Ghat, Nashik',
      ghat: 'Kalaram Temple Ghat',
      priceRange: '₹700 – ₹1,600',
      phone: '+91 99210 45678',
      overallScore: 84,
      rank: 8,
      whyRecommended: ['✓ Official Temple Purohit', '✓ Fast & organized family darshan'],
    },
    {
      id: 'pujari-9',
      name: 'Pandit Narayan Bhat',
      specialization: 'Vedic Chanting & Snan Sankalp',
      experienceYears: 11,
      rating: 4.5,
      reviewCount: 95,
      verificationBadge: 'Demo Data',
      languages: ['Hindi', 'Sanskrit'],
      location: 'Trimbakeshwar Ghat, Nashik',
      ghat: 'Trimbakeshwar Ghat',
      priceRange: '₹600 – ₹1,400',
      phone: '+91 98233 11223',
      overallScore: 82,
      rank: 9,
      whyRecommended: ['✓ Punctual service', '✓ Clear explanation of Snan importance'],
    },
    {
      id: 'pujari-10',
      name: 'Shri Madhav Puranik',
      specialization: 'Surya Arghya & Godavari Aarti',
      experienceYears: 10,
      rating: 4.4,
      reviewCount: 80,
      verificationBadge: 'Demo Data',
      languages: ['Marathi', 'Hindi'],
      location: 'Tapovan Ghat, Nashik',
      ghat: 'Tapovan Ghat',
      priceRange: '₹500 – ₹1,100',
      phone: '+91 94211 88990',
      overallScore: 80,
      rank: 10,
      whyRecommended: ['✓ Ideal for early morning Snan', '✓ Budget friendly ritual options'],
    },
  ];

  private drivers: Driver[] = [
    {
      id: 'driver-1',
      driverName: 'Ramesh Patil',
      vehicle: 'Bajaj RE Auto-Rickshaw (MH-15-BX-4921)',
      vehicleNo: 'MH-15-BX-4921',
      location: 'Nashik Railway Station Auto Stand',
      phone: '+91 98221 00112',
      rating: 4.9,
      reviewCount: 310,
      drivingScore: 95,
      verificationBadge: 'Verified',
      languages: ['Hindi', 'Marathi'],
      estimatedPrice: 'Official RTO Meter Rate (₹23 Base)',
      rank: 1,
      whyRecommended: ['✓ Always charges official RTO meter fare', '✓ 95/100 verified safe driving score', '✓ 12+ years experience in Nashik'],
    },
    {
      id: 'driver-2',
      driverName: 'Sanjay Deshmukh',
      vehicle: 'Maruti Dzire AC Taxi (MH-15-EF-8812)',
      vehicleNo: 'MH-15-EF-8812',
      location: 'College Road / Panchavati',
      phone: '+91 94220 33445',
      rating: 4.8,
      reviewCount: 220,
      drivingScore: 93,
      verificationBadge: 'Verified',
      languages: ['Hindi', 'English', 'Marathi'],
      estimatedPrice: '₹14/km AC Taxi Rate',
      rank: 2,
      whyRecommended: ['✓ Clean AC vehicle for family groups', '✓ Knows fast detour routes during peak Kumbh traffic'],
    },
    {
      id: 'driver-3',
      driverName: 'Ganesh More',
      vehicle: 'Shared Rickshaw Service (MH-15-CY-3310)',
      vehicleNo: 'MH-15-CY-3310',
      location: 'Ram Kund to Tapovan Shuttle Route',
      phone: '+91 98902 55667',
      rating: 4.8,
      reviewCount: 180,
      drivingScore: 91,
      verificationBadge: 'Verified',
      languages: ['Marathi', 'Hindi'],
      estimatedPrice: '₹20 per seat fixed shuttle',
      rank: 3,
      whyRecommended: ['✓ Frequent shuttle between main Ghats', '✓ Fixed low fare for budget travelers'],
    },
    {
      id: 'driver-4',
      driverName: 'Prakash Shinde',
      vehicle: 'E-Rickshaw Battery Auto (MH-15-ER-0192)',
      vehicleNo: 'MH-15-ER-0192',
      location: 'Panchavati Temple Corridor (Pedestrian Zone)',
      phone: '+91 97651 22334',
      rating: 4.7,
      reviewCount: 140,
      drivingScore: 90,
      verificationBadge: 'Verified',
      languages: ['Hindi', 'Marathi'],
      estimatedPrice: '₹15–₹30 short distance',
      rank: 4,
      whyRecommended: ['✓ Eco-friendly & quiet electric vehicle', '✓ Permitted inside inner temple pedestrian zones'],
    },
    {
      id: 'driver-5',
      driverName: 'Vijay Jadhav',
      vehicle: 'Toyota Ertiga 7-Seater (MH-15-HG-4455)',
      vehicleNo: 'MH-15-HG-4455',
      location: 'Nashik Airport / Central Bus Stand',
      phone: '+91 94233 66778',
      rating: 4.7,
      reviewCount: 160,
      drivingScore: 89,
      verificationBadge: 'Community Rated',
      languages: ['Hindi', 'English'],
      estimatedPrice: '₹2,200 full day booking',
      rank: 5,
      whyRecommended: ['✓ Ideal for large families with luggage', '✓ Luggage carrier & child seat support'],
    },
    {
      id: 'driver-6',
      driverName: 'Sunil Pawar',
      vehicle: 'Bajaj Maxima Auto (MH-15-DL-6721)',
      vehicleNo: 'MH-15-DL-6721',
      location: 'CBS Bus Stand, Nashik',
      phone: '+91 98811 77889',
      rating: 4.6,
      reviewCount: 115,
      drivingScore: 88,
      verificationBadge: 'Community Rated',
      languages: ['Hindi', 'Marathi'],
      estimatedPrice: 'Meter Fare + ₹10 luggage',
      rank: 6,
      whyRecommended: ['✓ Honest meter driver', '✓ Helps load heavy pilgrim bags'],
    },
    {
      id: 'driver-7',
      driverName: 'Mahesh Gaikwad',
      vehicle: 'E-Rickshaw Shuttle (MH-15-ER-4491)',
      vehicleNo: 'MH-15-ER-4491',
      location: 'Ram Kund Ghat Corridor',
      phone: '+91 93702 44556',
      rating: 4.6,
      reviewCount: 95,
      drivingScore: 87,
      verificationBadge: 'Official Source',
      languages: ['Marathi', 'Hindi'],
      estimatedPrice: '₹10 fixed ghat shuttle',
      rank: 7,
      whyRecommended: ['✓ Official Kumbh Mela Authority Registered Shuttle', '✓ Safe for elderly pilgrims'],
    },
    {
      id: 'driver-8',
      driverName: 'Anil Khairnar',
      vehicle: 'Tavera 9-Seater Van (MH-15-TV-9012)',
      vehicleNo: 'MH-15-TV-9012',
      location: 'Trimbakeshwar Road Stand',
      phone: '+91 99212 99001',
      rating: 4.5,
      reviewCount: 130,
      drivingScore: 86,
      verificationBadge: 'Verified',
      languages: ['Hindi', 'Gujarati'],
      estimatedPrice: '₹120 per head Trimbak trip',
      rank: 8,
      whyRecommended: ['✓ Direct group transport to Trimbakeshwar Temple', '✓ Fixed group rates'],
    },
    {
      id: 'driver-9',
      driverName: 'Santosh Thorat',
      vehicle: 'Auto-Rickshaw (MH-15-BX-1029)',
      vehicleNo: 'MH-15-BX-1029',
      location: 'Sharanpur Road Market',
      phone: '+91 98234 55443',
      rating: 4.5,
      reviewCount: 88,
      drivingScore: 84,
      verificationBadge: 'Demo Data',
      languages: ['Hindi', 'Marathi'],
      estimatedPrice: 'Meter Fare',
      rank: 9,
      whyRecommended: ['✓ Reliable local market trips', '✓ Friendly attitude'],
    },
    {
      id: 'driver-10',
      driverName: 'Dnyaneshwar Shinde',
      vehicle: 'Auto-Rickshaw (MH-15-CY-7788)',
      vehicleNo: 'MH-15-CY-7788',
      location: 'Satpur / MIDC Bus Stop',
      phone: '+91 94212 33221',
      rating: 4.4,
      reviewCount: 70,
      drivingScore: 82,
      verificationBadge: 'Demo Data',
      languages: ['Marathi', 'Hindi'],
      estimatedPrice: 'Meter Fare',
      rank: 10,
      whyRecommended: ['✓ Quick response', '✓ Clean vehicle'],
    },
  ];

  private hotels: Hotel[] = [
    {
      id: 'hotel-1',
      name: 'Hotel Krishna Bhavan Pilgrim Stay',
      rating: 4.8,
      reviewCount: 410,
      pricePerNight: 1450,
      distanceToGhatKm: 0.6,
      amenities: ['Free WiFi', 'Pure Veg Restaurant', '24/7 Hot Water', 'Elevator', 'Pilgrim Desk'],
      familyFriendly: true,
      childrenFriendly: true,
      parking: true,
      foodAvailable: true,
      location: 'Panchavati, Nashik (600m from Ram Kund)',
      phone: '+91 253 257 1234',
      verificationBadge: 'Verified',
      rank: 1,
      whyRecommended: ['✓ 600m walking distance to Ram Kund Ghat', '✓ 100% Pure Satvik Veg Restaurant', '✓ Clean family suites'],
    },
    {
      id: 'hotel-2',
      name: 'The Gateway Hotel Ambad Nashik (Taj)',
      rating: 4.9,
      reviewCount: 850,
      pricePerNight: 6800,
      distanceToGhatKm: 8.5,
      amenities: ['5-Star Luxury', 'Swimming Pool', 'Spa', 'Multi-Cuisine', 'Free Valet Parking'],
      familyFriendly: true,
      childrenFriendly: true,
      parking: true,
      foodAvailable: true,
      location: 'Ambad, Nashik',
      phone: '+91 253 669 2300',
      verificationBadge: 'Verified',
      rank: 2,
      whyRecommended: ['✓ 5-Star luxury hospitality', '✓ Excellent security & concierge service for Kumbh visitors'],
    },
    {
      id: 'hotel-3',
      name: 'Godavari Retreat Yatri Niwas',
      rating: 4.7,
      reviewCount: 290,
      pricePerNight: 950,
      distanceToGhatKm: 0.9,
      amenities: ['Clean Beds', 'Hot Water', 'Filtered Drinking Water', 'Luggage Storage'],
      familyFriendly: true,
      childrenFriendly: true,
      parking: false,
      foodAvailable: true,
      location: 'Old Nashik near Godavari Ghat',
      phone: '+91 253 258 9900',
      verificationBadge: 'Verified',
      rank: 3,
      whyRecommended: ['✓ Budget friendly under ₹1,000/night', '✓ Very close to Snan Ghats'],
    },
    {
      id: 'hotel-4',
      name: 'Hotel Express Inn Luxury Residency',
      rating: 4.8,
      reviewCount: 620,
      pricePerNight: 4200,
      distanceToGhatKm: 5.2,
      amenities: ['4-Star Standard', 'Gym', 'Breakfast Buffet', 'Air Conditioning'],
      familyFriendly: true,
      childrenFriendly: true,
      parking: true,
      foodAvailable: true,
      location: 'Mumbai-Agra Highway, Nashik',
      phone: '+91 253 222 7777',
      verificationBadge: 'Verified',
      rank: 4,
      whyRecommended: ['✓ Highly rated 4-star comfort', '✓ Easy highway access avoiding city gridlock'],
    },
    {
      id: 'hotel-5',
      name: 'Shri Ram Ashram Yatri Niwas',
      rating: 4.6,
      reviewCount: 340,
      pricePerNight: 600,
      distanceToGhatKm: 0.4,
      amenities: ['Dharmashala Beds', 'Common Hot Shower', 'Rooftop Prayer Area'],
      familyFriendly: true,
      childrenFriendly: true,
      parking: false,
      foodAvailable: false,
      location: 'Ram Kund Bank, Nashik',
      phone: '+91 253 251 4321',
      verificationBadge: 'Official Source',
      rank: 5,
      whyRecommended: ['✓ Official Charitable Ashram Yatri Niwas', '✓ 400m from Ram Kund', '✓ Ultra budget friendly'],
    },
    {
      id: 'hotel-6',
      name: 'Hotel Radhika Inn',
      rating: 4.6,
      reviewCount: 180,
      pricePerNight: 1850,
      distanceToGhatKm: 2.1,
      amenities: ['AC Rooms', 'Room Service', 'WiFi', 'Veg Breakfast'],
      familyFriendly: true,
      childrenFriendly: true,
      parking: true,
      foodAvailable: true,
      location: 'College Road, Nashik',
      phone: '+91 253 231 8899',
      verificationBadge: 'Community Rated',
      rank: 6,
      whyRecommended: ['✓ Located in modern shopping area', '✓ Clean AC deluxe rooms'],
    },
    {
      id: 'hotel-7',
      name: 'Panchavati Elite Residency',
      rating: 4.5,
      reviewCount: 150,
      pricePerNight: 2200,
      distanceToGhatKm: 1.2,
      amenities: ['Family Quad Rooms', 'AC', 'Elevator', 'Travel Desk'],
      familyFriendly: true,
      childrenFriendly: true,
      parking: true,
      foodAvailable: true,
      location: 'Panchavati Karanja, Nashik',
      phone: '+91 253 252 6600',
      verificationBadge: 'Community Rated',
      rank: 7,
      whyRecommended: ['✓ Family quad beds for 4 adults', '✓ 1.2km walk to main bathing ghats'],
    },
    {
      id: 'hotel-8',
      name: 'Hotel Bliss Regency',
      rating: 4.5,
      reviewCount: 130,
      pricePerNight: 1200,
      distanceToGhatKm: 3.0,
      amenities: ['AC Rooms', '24h Front Desk', 'Veg Food'],
      familyFriendly: true,
      childrenFriendly: false,
      parking: true,
      foodAvailable: true,
      location: 'CBS Circle, Nashik',
      phone: '+91 253 250 1122',
      verificationBadge: 'Demo Data',
      rank: 8,
      whyRecommended: ['✓ Near central bus stand', '✓ Good budget choice'],
    },
    {
      id: 'hotel-9',
      name: 'Trimbak Pilgrimage Homestay',
      rating: 4.4,
      reviewCount: 90,
      pricePerNight: 1100,
      distanceToGhatKm: 1.5,
      amenities: ['Homestay Comfort', 'Home Cooked Meals', 'Geyser'],
      familyFriendly: true,
      childrenFriendly: true,
      parking: true,
      foodAvailable: true,
      location: 'Trimbakeshwar Town',
      phone: '+91 94220 99887',
      verificationBadge: 'Demo Data',
      rank: 9,
      whyRecommended: ['✓ Warm local family hospitality', '✓ Home cooked Maharashtrian Thali'],
    },
    {
      id: 'hotel-10',
      name: 'Godavari Tourist Lodge',
      rating: 4.3,
      reviewCount: 75,
      pricePerNight: 750,
      distanceToGhatKm: 1.0,
      amenities: ['Basic Rooms', 'Attached Bath', 'Hot Water'],
      familyFriendly: false,
      childrenFriendly: false,
      parking: false,
      foodAvailable: false,
      location: 'Old Nashik Bazaar',
      phone: '+91 253 259 4433',
      verificationBadge: 'Demo Data',
      rank: 10,
      whyRecommended: ['✓ Simple non-AC lodging', '✓ Cheap night stay'],
    },
  ];

  private locations: KumbhLocation[] = [
    {
      id: 'loc-1',
      name: 'Ram Kund (Main Sacred Snan Ghat)',
      type: 'ghat',
      description: 'The holiest bathing ghat on the banks of Godavari River where Lord Rama performed rituals during his exile. Site of Shahi Snan.',
      location: 'Panchavati, Nashik',
      timing: 'Open 24 Hours (Best: 4:00 AM – 8:00 AM)',
      bestTimeToVisit: 'Early Morning Sunrise for Mahasnan & Ganga-Godavari Aarti',
    },
    {
      id: 'loc-2',
      name: 'Shree Kalaram Temple',
      type: 'temple',
      description: 'Ancient black stone temple dedicated to Lord Rama, built in 1782 by Sardar Rangarao Odhekar. Features 70-foot tall black stone spire.',
      location: 'Panchavati, Nashik',
      timing: '5:30 AM – 10:00 PM',
      bestTimeToVisit: 'Morning Kakad Aarti (6:00 AM) or Evening Shej Aarti',
    },
    {
      id: 'loc-3',
      name: 'Trimbakeshwar Jyotirlinga Temple',
      type: 'temple',
      description: 'One of the 12 sacred Jyotirlingas of Lord Shiva and the official source of Godavari River at Brahmagiri hill.',
      location: 'Trimbak Town (28 km from Nashik)',
      timing: '5:30 AM – 9:00 PM',
      bestTimeToVisit: 'Early morning weekdays to avoid 3+ hour weekend queues',
    },
    {
      id: 'loc-4',
      name: 'Sita Gufa (Sita Cave)',
      type: 'temple',
      description: 'Sacred cave near Panchavati where Goddess Sita stayed and worshipped Lord Shiva. Near the site of Ravana’s abduction episode.',
      location: 'Panchavati, Nashik',
      timing: '6:00 AM – 8:00 PM',
      bestTimeToVisit: '9:00 AM – 11:00 AM',
    },
    {
      id: 'loc-5',
      name: 'Tapovan & Laxman Rekha Ghat',
      type: 'ghat',
      description: 'Serene penance ground of ancient sages with lush trees on Godavari banks. Site where Laxman cut Surpanakha’s nose.',
      location: 'Tapovan, Nashik',
      timing: 'Open 24 Hours',
      bestTimeToVisit: 'Late Afternoon 4:00 PM – 6:30 PM for sunset walk',
    },
    {
      id: 'loc-6',
      name: 'Sadhugram (Saint Encampment Area)',
      type: 'ritual',
      description: 'Sprawling 300+ acre city of tents accommodating thousands of Sadhus, Akharas, Mahant Gurus, and spiritual discourses.',
      location: 'Tapovan - Sharanpur Grounds',
      timing: 'Open 24 Hours during Kumbh Mela',
      bestTimeToVisit: '10:00 AM – 1:00 PM for Akhara Pravachan & Darshan',
    },
    {
      id: 'loc-7',
      name: 'Authentic Maharashtrian Thali House',
      type: 'food',
      description: 'Famous local dining spot serving authentic Pithla Bhakri, Bharli Vangi, Sol Kadhi, and Satvik Puri Bhaji for pilgrims.',
      location: 'College Road Market, Nashik',
      timing: '11:30 AM – 10:30 PM',
      bestTimeToVisit: 'Lunch 12:30 PM – 2:30 PM',
    },
    {
      id: 'loc-8',
      name: 'Kumbh Emergency & Medical Health Post',
      type: 'emergency',
      description: '24/7 Red Cross & District Health Department medical center with free doctor consultation, first aid, and ambulance dispatch.',
      location: 'Ram Kund Entrance & CBS Circle',
      timing: 'Open 24 Hours Helpline: 108 / +91 253 231 0000',
      bestTimeToVisit: 'Emergency round-the-clock availability',
    },
  ];

  public getTopPujaris(ghatFilter?: string): Pujari[] {
    let list = [...this.pujaris];
    if (ghatFilter && ghatFilter !== 'all') {
      list = list.filter((p) => p.ghat.toLowerCase().includes(ghatFilter.toLowerCase()));
    }
    return list.sort((a, b) => a.rank - b.rank);
  }

  public getTopDrivers(): Driver[] {
    return [...this.drivers].sort((a, b) => a.rank - b.rank);
  }

  public getTopHotels(filter?: { budget?: string; familyOnly?: boolean }): Hotel[] {
    let list = [...this.hotels];
    if (filter) {
      if (filter.budget === 'budget') {
        list = list.filter((h) => h.pricePerNight <= 1500);
      } else if (filter.budget === 'mid') {
        list = list.filter((h) => h.pricePerNight > 1500 && h.pricePerNight <= 3500);
      } else if (filter.budget === 'premium') {
        list = list.filter((h) => h.pricePerNight > 3500);
      }
      if (filter.familyOnly) {
        list = list.filter((h) => h.familyFriendly);
      }
    }
    return list.sort((a, b) => a.rank - b.rank);
  }

  public getLocations(type?: string): KumbhLocation[] {
    if (type && type !== 'all') {
      return this.locations.filter((l) => l.type === type);
    }
    return this.locations;
  }
}

export const kumbhService = new KumbhService();
