import { ProductAnalysisFull, IdentifiedProduct, PriceObservation, AppSettings, RetailerStoreOption } from '../types';

export const initialSettings: AppSettings = {
  demoMode: true,
  currency: '₹',
  defaultCity: 'Nashik',
  defaultState: 'Maharashtra',
  cacheFreshnessMinutes: 15,
  fairPriceThresholdPercent: 10,
  geminiApiKeyConfigured: false,
};

export const sampleProductsDatabase: ProductAnalysisFull[] = [
  {
    id: 'prod-headphones-x',
    product: {
      id: 'prod-headphones-x',
      name: 'Sony WH-CH720N Wireless Headphones',
      brand: 'Sony',
      model: 'WH-CH720N',
      category: 'Audio / Headphones',
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
      confidence: 94,
      description: 'Over-ear Noise Canceling Bluetooth Headphones with Integrated V1 Processor.',
      specifications: [
        { name: 'Connectivity', value: 'Bluetooth 5.2 / 3.5mm Aux' },
        { name: 'Active Noise Cancellation', value: 'Yes (Dual Noise Sensor)' },
        { name: 'Battery Life', value: 'Up to 35 Hours (ANC On)' },
        { name: 'Weight', value: '192 grams (Ultra Lightweight)' },
        { name: 'Warranty', value: '1 Year Brand Warranty' },
      ],
    },
    quotedPrice: 1350,
    location: {
      city: 'Nashik',
      state: 'Maharashtra',
      country: 'India',
      locality: 'College Road',
      source: 'manual',
      formatted: 'Nashik, Maharashtra',
    },
    priceIntelligence: {
      sellerPrice: 1350,
      fairPriceMin: 1150,
      fairPriceMax: 1250,
      marketMedian: 1199,
      marketAverage: 1205,
      lowestObserved: 1099,
      highestObserved: 1299,
      fairnessScore: 72,
      status: 'HIGH',
      statusLabel: '⚠ ABOVE FAIR RANGE',
      priceDeltaPercent: 12.6,
      distribution: [
        { price: 1099, label: '₹1,099 (Lowest)', count: 2 },
        { price: 1149, label: '₹1,149', count: 5 },
        { price: 1199, label: '₹1,199 (Median)', count: 8 },
        { price: 1249, label: '₹1,249', count: 4 },
        { price: 1299, label: '₹1,299 (Highest)', count: 2 },
      ],
      sourcesAnalyzedCount: 18,
      lastUpdatedText: 'Updated 4 minutes ago',
      confidenceScore: 91,
    },
    priceObservations: [
      {
        id: 'obs-1',
        productId: 'prod-headphones-x',
        seller: 'Electronic Paradise Local Store',
        source: 'College Road Market, Nashik',
        sourceType: 'local_store',
        price: 1350,
        currency: '₹',
        location: 'Nashik, Maharashtra',
        availability: 'in_stock',
        condition: 'new',
        warranty: '1 Year Official',
        shipping: 0,
        timestamp: new Date(Date.now() - 4 * 60000).toISOString(),
        isLive: true,
      },
    ],
    whereToBuy: [
      {
        id: 'store-1',
        storeName: 'Amazon India Direct',
        storeLogoUrl: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=100&auto=format&fit=crop&q=80',
        channelType: 'online',
        price: 1199,
        currency: '₹',
        availability: 'In Stock',
        location: 'Pan-India (Fast Delivery)',
        warranty: '1 Year Official Sony Warranty',
        storeUrl: 'https://amazon.in',
      },
      {
        id: 'store-2',
        storeName: 'Flipkart Electronics',
        storeLogoUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=100&auto=format&fit=crop&q=80',
        channelType: 'online',
        price: 1149,
        currency: '₹',
        availability: 'Fast Delivery',
        location: 'Pan-India',
        warranty: '1 Year Official Warranty',
        storeUrl: 'https://flipkart.com',
      },
      {
        id: 'store-3',
        storeName: 'Croma Retail Nashik City Center',
        storeLogoUrl: 'https://images.unsplash.com/photo-1555421689-491a97ff2040?w=100&auto=format&fit=crop&q=80',
        channelType: 'authorized_dealer',
        price: 1249,
        currency: '₹',
        availability: 'In Stock',
        location: 'City Center Mall, Nashik',
        warranty: '1 Year Brand Warranty',
        storeUrl: 'https://croma.com',
      },
      {
        id: 'store-4',
        storeName: 'Vijay Sales Nashik Store',
        storeLogoUrl: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=100&auto=format&fit=crop&q=80',
        channelType: 'authorized_dealer',
        price: 1099,
        currency: '₹',
        availability: 'Limited Stock',
        location: 'College Road, Nashik',
        warranty: '1 Year Brand Warranty',
        storeUrl: 'https://vijaysales.com',
      },
    ],
    reviews: {
      overallRating: 4.2,
      totalReviewsCount: 1248,
      reviewConfidenceScore: 88,
      positivePercent: 78,
      neutralPercent: 14,
      negativePercent: 8,
      pros: [
        'Excellent build quality and lightweight ergonomic headband',
        'Impressive 35-hour battery life with quick charge feature',
      ],
      cons: [
        'Ear pads can get slightly warm during prolonged usage',
      ],
      aspects: [
        { name: 'Durability', score: 88, sentiment: 'positive' },
        { name: 'Battery Life', score: 94, sentiment: 'positive' },
      ],
      webReviews: [
        {
          id: 'rev-sample-1',
          author: 'Aarav Mehta',
          rating: 5,
          date: '2 days ago',
          source: 'Amazon India Verified Buyer',
          comment: 'Extremely good active noise cancellation for travelling.',
          sentiment: 'positive',
          verified: true,
        },
      ],
    },
    valueAnalysis: {
      qualityScore: 88,
      featuresScore: 82,
      reviewsScore: 84,
      priceScore: 61,
      overallValueScore: 78,
      valueStatement: 'Good value if purchased below ₹1,250.',
    },
    buyingDecision: {
      recommendation: 'CONSIDER',
      overallScore: 68,
      reason: 'The product is good, but the current quoted price of ₹1,350 is approximately 12.6% above the estimated fair market range (₹1,150 – ₹1,250).',
      decisionConfidence: 86,
      componentScores: {
        price: 55,
        quality: 86,
        reviews: 84,
        value: 67,
        availability: 91,
      },
      confidenceBreakdown: {
        productMatchScore: 94,
        productMatchLevel: 'High confidence',
        productDetails: {
          categoryMatched: true,
          brandDetected: true,
          modelDetected: true,
          specsMatched: true,
          webVerified: true,
        },
        priceDataScore: 88,
        priceDataLevel: 'High confidence',
        reviewScore: 84,
        reviewLevel: 'High confidence',
        decisionScore: 86,
        decisionLevel: 'Good confidence',
        weights: { product: 30, price: 30, review: 20, freshness: 10, agreement: 10 },
        explanationNotes: ['Product matched', 'Price verified', 'Reviews analyzed'],
      },
      whyThisPrice: {
        marketMedian: 1199,
        observedRange: '₹1,099 – ₹1,299',
        reviewScore: 4.2,
        quality: 'High (Verified Sony V1 Audio Engine)',
        location: 'Nashik, Maharashtra',
        warranty: '1 Year Brand Official Warranty',
        marketConfidence: 91,
        simpleExplanation: 'FairBuy estimates this fair range from 18 market signals in Nashik and online channels.',
      },
    },
    alternatives: [],
    timestamp: new Date().toISOString(),
  },
];
